/*********************************************************************
* The code in this file is generated by the editor.  Do not modify!  *
*********************************************************************/

#include "GameBase.Private.hpp"

//#<<BEHAVIOR_INCLUDES>>


template<typename T> recondite::Behavior* __CreateBehavior(){return new T();}

void GameBase::Register(rEngine* engine){
//#<<BEHAVIOR_DEFINES>>
}
